spring:
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: true
    ignore-missing-migrations: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
