---
replicaCount: 1

app:
  namespace: inventorymanagement
  local_deployment: true
  kong:
    enabled: true
    path: "/"

image:
  repository:
    "localhost:5000/inventory-management-ui"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
