---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: inventory-api-ingress
  namespace: {{.Values.app.namespace}}
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "false"
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "true"
spec:
  rules:
    - http:
        paths:
          - path: {{.Values.app.kong.path}}
            backend:
              serviceName: {{include "inventorymanagement.fullname" .}}
              servicePort: {{.Values.service.port}}
