---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{.Values.app.namespace}}
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - name: {{.Values.postgres.serviceport.name}}
      port: {{.Values.postgres.serviceport.port}}
      nodePort: {{.Values.postgres.serviceport.nodePort}}
      protocol: {{.Values.postgres.serviceport.protocol}}
      targetPort: {{.Values.postgres.serviceport.targetPort}}
  selector:
    app: postgres
