---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.app.namespace}}
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
  name: {{include "inventorymanagement.fullname" .}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Chart.Name}}
      app.kubernetes.io/version: {{.Chart.Version}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Chart.Name}}
        app.kubernetes.io/version: {{.Chart.Version}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.service.port}}
              name: http
              protocol: TCP
          volumeMounts:
            - name: inventorymanagement-config-volume
              mountPath: /opt/deployments/config
      volumes:
        - name: inventorymanagement-config-volume

